// GENERATED by scripts/gen-css-types.mjs from filter-panel.module.css — do not edit.
// Source: packages/theme/src/widgets/filter-panel/filter-panel.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly actions: string;
  readonly count: string;
  readonly query: string;
  readonly root: string;
};
export default styles;
