// GENERATED by scripts/gen-css-types.mjs from field.module.css — do not edit.
// Source: packages/theme/src/components/field/field.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly description: string;
  readonly error: string;
  readonly item: string;
  readonly label: string;
  readonly root: string;
};
export default styles;
