// GENERATED by scripts/gen-css-types.mjs from form.module.css — do not edit.
// Source: packages/theme/src/components/field/form.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly root: string;
};
export default styles;
