// GENERATED by scripts/gen-css-types.mjs from popover.module.css — do not edit.
// Source: packages/theme/src/components/popover/popover.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly arrow: string;
  readonly description: string;
  readonly popup: string;
  readonly positioner: string;
  readonly title: string;
};
export default styles;
