// GENERATED by scripts/gen-css-types.mjs from spinner.module.css — do not edit.
// Source: packages/theme/src/components/spinner/spinner.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly arc: string;
  readonly glyph: string;
  readonly root: string;
  readonly sizeLg: string;
  readonly sizeSm: string;
  readonly track: string;
};
export default styles;
