// GENERATED by scripts/gen-css-types.mjs from dialog.module.css — do not edit.
// Source: packages/theme/src/components/dialog/dialog.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly backdrop: string;
  readonly description: string;
  readonly dismiss: string;
  readonly footer: string;
  readonly popup: string;
  readonly sizeFullscreen: string;
  readonly sizeLg: string;
  readonly sizeSm: string;
  readonly title: string;
  readonly viewport: string;
  readonly viewportFullscreen: string;
};
export default styles;
