// GENERATED by scripts/gen-css-types.mjs from number-field.module.css — do not edit.
// Source: packages/theme/src/components/number-field/number-field.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly decrement: string;
  readonly group: string;
  readonly increment: string;
  readonly input: string;
  readonly root: string;
  readonly scrubArea: string;
  readonly sizeLg: string;
  readonly sizeSm: string;
  readonly stepper: string;
};
export default styles;
