// GENERATED by scripts/gen-css-types.mjs from progress-tracker.module.css — do not edit.
// Source: packages/theme/src/widgets/progress-tracker/progress-tracker.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly announcement: string;
  readonly announcementDanger: string;
  readonly empty: string;
  readonly marker: string;
  readonly root: string;
  readonly step: string;
  readonly stepCurrent: string;
  readonly stepDone: string;
  readonly stepFailed: string;
  readonly stepLabel: string;
  readonly steps: string;
};
export default styles;
