// GENERATED by scripts/gen-css-types.mjs from toggle-group.module.css — do not edit.
// Source: packages/theme/src/components/toggle-group/toggle-group.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly group: string;
  readonly groupChips: string;
  readonly groupSizeSm: string;
  readonly toggle: string;
};
export default styles;
