// GENERATED by scripts/gen-css-types.mjs from text.module.css — do not edit.
// Source: packages/theme/src/components/text/text.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly mono: string;
  readonly root: string;
  readonly sizeLg: string;
  readonly sizeSm: string;
  readonly sizeXl: string;
  readonly sizeXs: string;
  readonly toneAccent: string;
  readonly toneDanger: string;
  readonly toneMuted: string;
  readonly toneSecondary: string;
  readonly toneSuccess: string;
  readonly truncate: string;
  readonly weightMedium: string;
  readonly weightSemibold: string;
};
export default styles;
