// GENERATED by scripts/gen-css-types.mjs from toast.module.css — do not edit.
// Source: packages/theme/src/components/toast/toast.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly action: string;
  readonly close: string;
  readonly content: string;
  readonly description: string;
  readonly icon: string;
  readonly root: string;
  readonly title: string;
  readonly viewport: string;
};
export default styles;
