// GENERATED by scripts/gen-css-types.mjs from tabs.module.css — do not edit.
// Source: packages/theme/src/components/tabs/tabs.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly indicator: string;
  readonly list: string;
  readonly panel: string;
  readonly root: string;
  readonly tab: string;
};
export default styles;
