// GENERATED by scripts/gen-css-types.mjs from skeleton.module.css — do not edit.
// Source: packages/theme/src/components/skeleton/skeleton.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly block: string;
  readonly circle: string;
  readonly lines: string;
  readonly root: string;
  readonly text: string;
};
export default styles;
