// GENERATED by scripts/gen-css-types.mjs from menu.module.css — do not edit.
// Source: packages/theme/src/components/menu/menu.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly group: string;
  readonly groupLabel: string;
  readonly item: string;
  readonly itemIndicator: string;
  readonly itemLabel: string;
  readonly popup: string;
  readonly positioner: string;
  readonly radioDot: string;
  readonly selectableItem: string;
  readonly separator: string;
  readonly submenuChevron: string;
  readonly submenuTrigger: string;
  readonly trigger: string;
  readonly triggerGhost: string;
  readonly triggerSizeSm: string;
};
export default styles;
