// GENERATED by scripts/gen-css-types.mjs from switch.module.css — do not edit.
// Source: packages/theme/src/components/switch/switch.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly root: string;
  readonly thumb: string;
};
export default styles;
