// GENERATED by scripts/gen-css-types.mjs from input.module.css — do not edit.
// Source: packages/theme/src/components/input/input.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly affix: string;
  readonly control: string;
  readonly multiline: string;
  readonly root: string;
  readonly sizeLg: string;
  readonly sizeSm: string;
  readonly textarea: string;
};
export default styles;
