// GENERATED by scripts/gen-css-types.mjs from radio-group.module.css — do not edit.
// Source: packages/theme/src/components/radio-group/radio-group.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly group: string;
  readonly indicator: string;
  readonly radio: string;
};
export default styles;
