// GENERATED by scripts/gen-css-types.mjs from poll.module.css — do not edit.
// Source: packages/theme/src/widgets/poll/poll.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly footer: string;
  readonly noneRow: string;
  readonly notice: string;
  readonly optionDescription: string;
  readonly optionLabel: string;
  readonly optionRow: string;
  readonly optionTitle: string;
  readonly question: string;
  readonly root: string;
};
export default styles;
