// GENERATED by scripts/gen-css-types.mjs from icons.module.css — do not edit.
// Source: packages/theme/src/components/icons/icons.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly glyph: string;
};
export default styles;
