// GENERATED by scripts/gen-css-types.mjs from choice-chips.module.css — do not edit.
// Source: packages/theme/src/widgets/choice-chips/choice-chips.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly choices: string;
  readonly footer: string;
  readonly notice: string;
  readonly prompt: string;
  readonly root: string;
};
export default styles;
