// GENERATED by scripts/gen-css-types.mjs from alert-dialog.module.css — do not edit.
// Source: packages/theme/src/components/alert-dialog/alert-dialog.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly backdrop: string;
  readonly description: string;
  readonly footer: string;
  readonly popup: string;
  readonly title: string;
  readonly toneDanger: string;
  readonly viewport: string;
};
export default styles;
