// GENERATED by scripts/gen-css-types.mjs from combobox.module.css — do not edit.
// Source: packages/theme/src/components/combobox/combobox.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly clear: string;
  readonly empty: string;
  readonly emptyMessage: string;
  readonly fieldButton: string;
  readonly group: string;
  readonly groupLabel: string;
  readonly input: string;
  readonly inputGroup: string;
  readonly item: string;
  readonly itemIndicator: string;
  readonly list: string;
  readonly popup: string;
  readonly positioner: string;
};
export default styles;
