// GENERATED by scripts/gen-tokens.mjs from packages/theme/src/tokens.css — do not edit.
// Run `npm run gen:tokens` after changing a token. CI drift-checks this file (ADR 0024).

/** Every `--nerey-*` custom property declared by the theme. */
export type NereyToken =
  | '--nerey-color-slate-50'
  | '--nerey-color-slate-100'
  | '--nerey-color-slate-200'
  | '--nerey-color-slate-300'
  | '--nerey-color-slate-400'
  | '--nerey-color-slate-500'
  | '--nerey-color-slate-600'
  | '--nerey-color-slate-700'
  | '--nerey-color-slate-800'
  | '--nerey-color-slate-900'
  | '--nerey-color-slate-950'
  | '--nerey-color-teal-50'
  | '--nerey-color-teal-100'
  | '--nerey-color-teal-200'
  | '--nerey-color-teal-300'
  | '--nerey-color-teal-400'
  | '--nerey-color-teal-500'
  | '--nerey-color-teal-600'
  | '--nerey-color-teal-700'
  | '--nerey-color-teal-800'
  | '--nerey-color-teal-900'
  | '--nerey-color-teal-950'
  | '--nerey-color-red-100'
  | '--nerey-color-red-300'
  | '--nerey-color-red-500'
  | '--nerey-color-red-600'
  | '--nerey-color-red-700'
  | '--nerey-color-red-950'
  | '--nerey-color-amber-100'
  | '--nerey-color-amber-300'
  | '--nerey-color-amber-500'
  | '--nerey-color-amber-700'
  | '--nerey-color-amber-950'
  | '--nerey-color-green-100'
  | '--nerey-color-green-300'
  | '--nerey-color-green-500'
  | '--nerey-color-green-700'
  | '--nerey-color-green-950'
  | '--nerey-color-white'
  | '--nerey-color-black'
  | '--nerey-space-0'
  | '--nerey-space-1'
  | '--nerey-space-2'
  | '--nerey-space-3'
  | '--nerey-space-4'
  | '--nerey-space-5'
  | '--nerey-space-6'
  | '--nerey-space-8'
  | '--nerey-space-10'
  | '--nerey-space-12'
  | '--nerey-space-16'
  | '--nerey-radius-none'
  | '--nerey-radius-sm'
  | '--nerey-radius-md'
  | '--nerey-radius-lg'
  | '--nerey-radius-xl'
  | '--nerey-radius-2xl'
  | '--nerey-radius-full'
  | '--nerey-font-sans'
  | '--nerey-font-mono'
  | '--nerey-font-size-xs'
  | '--nerey-font-size-sm'
  | '--nerey-font-size-md'
  | '--nerey-font-size-lg'
  | '--nerey-font-size-xl'
  | '--nerey-line-height-tight'
  | '--nerey-line-height-normal'
  | '--nerey-line-height-relaxed'
  | '--nerey-font-weight-normal'
  | '--nerey-font-weight-medium'
  | '--nerey-font-weight-semibold'
  | '--nerey-letter-spacing-wide'
  | '--nerey-duration-instant'
  | '--nerey-duration-fast'
  | '--nerey-duration-normal'
  | '--nerey-ease-standard'
  | '--nerey-ease-emphasized'
  | '--nerey-z-raised'
  | '--nerey-z-sticky'
  | '--nerey-z-overlay'
  | '--nerey-z-popover'
  | '--nerey-z-toast'
  | '--nerey-control-height-sm'
  | '--nerey-control-height-md'
  | '--nerey-control-height-lg'
  | '--nerey-border-width'
  | '--nerey-focus-ring-width'
  | '--nerey-focus-ring-offset'
  | '--nerey-widget-max-width'
  | '--nerey-surface-canvas'
  | '--nerey-surface-raised'
  | '--nerey-surface-sunken'
  | '--nerey-surface-muted'
  | '--nerey-surface-inverse'
  | '--nerey-surface-accent-subtle'
  | '--nerey-surface-accent'
  | '--nerey-surface-accent-hover'
  | '--nerey-surface-danger-subtle'
  | '--nerey-surface-danger'
  | '--nerey-surface-danger-hover'
  | '--nerey-surface-success-subtle'
  | '--nerey-surface-warning-subtle'
  | '--nerey-surface-hover'
  | '--nerey-surface-selected'
  | '--nerey-surface-scrim'
  | '--nerey-text-primary'
  | '--nerey-text-secondary'
  | '--nerey-text-muted'
  | '--nerey-text-disabled'
  | '--nerey-text-inverse'
  | '--nerey-text-on-accent'
  | '--nerey-text-accent'
  | '--nerey-text-danger'
  | '--nerey-text-success'
  | '--nerey-text-warning'
  | '--nerey-text-link'
  | '--nerey-border-subtle'
  | '--nerey-border-default'
  | '--nerey-border-strong'
  | '--nerey-border-accent'
  | '--nerey-border-danger'
  | '--nerey-border-focus'
  | '--nerey-shadow-sm'
  | '--nerey-shadow-md'
  | '--nerey-shadow-lg'
  | '--nerey-opacity-dimmed'
  | '--nerey-opacity-disabled';

/**
 * The subset a component stylesheet may read. Primitive ramps (`--nerey-color-*`) are
 * excluded on purpose: components read the semantic layer so a re-theme is a value swap
 * rather than a find-and-replace (ADR 0024).
 */
export type NereySemanticToken =
  | '--nerey-space-0'
  | '--nerey-space-1'
  | '--nerey-space-2'
  | '--nerey-space-3'
  | '--nerey-space-4'
  | '--nerey-space-5'
  | '--nerey-space-6'
  | '--nerey-space-8'
  | '--nerey-space-10'
  | '--nerey-space-12'
  | '--nerey-space-16'
  | '--nerey-radius-none'
  | '--nerey-radius-sm'
  | '--nerey-radius-md'
  | '--nerey-radius-lg'
  | '--nerey-radius-xl'
  | '--nerey-radius-2xl'
  | '--nerey-radius-full'
  | '--nerey-font-sans'
  | '--nerey-font-mono'
  | '--nerey-font-size-xs'
  | '--nerey-font-size-sm'
  | '--nerey-font-size-md'
  | '--nerey-font-size-lg'
  | '--nerey-font-size-xl'
  | '--nerey-line-height-tight'
  | '--nerey-line-height-normal'
  | '--nerey-line-height-relaxed'
  | '--nerey-font-weight-normal'
  | '--nerey-font-weight-medium'
  | '--nerey-font-weight-semibold'
  | '--nerey-letter-spacing-wide'
  | '--nerey-duration-instant'
  | '--nerey-duration-fast'
  | '--nerey-duration-normal'
  | '--nerey-ease-standard'
  | '--nerey-ease-emphasized'
  | '--nerey-z-raised'
  | '--nerey-z-sticky'
  | '--nerey-z-overlay'
  | '--nerey-z-popover'
  | '--nerey-z-toast'
  | '--nerey-control-height-sm'
  | '--nerey-control-height-md'
  | '--nerey-control-height-lg'
  | '--nerey-border-width'
  | '--nerey-focus-ring-width'
  | '--nerey-focus-ring-offset'
  | '--nerey-widget-max-width'
  | '--nerey-surface-canvas'
  | '--nerey-surface-raised'
  | '--nerey-surface-sunken'
  | '--nerey-surface-muted'
  | '--nerey-surface-inverse'
  | '--nerey-surface-accent-subtle'
  | '--nerey-surface-accent'
  | '--nerey-surface-accent-hover'
  | '--nerey-surface-danger-subtle'
  | '--nerey-surface-danger'
  | '--nerey-surface-danger-hover'
  | '--nerey-surface-success-subtle'
  | '--nerey-surface-warning-subtle'
  | '--nerey-surface-hover'
  | '--nerey-surface-selected'
  | '--nerey-surface-scrim'
  | '--nerey-text-primary'
  | '--nerey-text-secondary'
  | '--nerey-text-muted'
  | '--nerey-text-disabled'
  | '--nerey-text-inverse'
  | '--nerey-text-on-accent'
  | '--nerey-text-accent'
  | '--nerey-text-danger'
  | '--nerey-text-success'
  | '--nerey-text-warning'
  | '--nerey-text-link'
  | '--nerey-border-subtle'
  | '--nerey-border-default'
  | '--nerey-border-strong'
  | '--nerey-border-accent'
  | '--nerey-border-danger'
  | '--nerey-border-focus'
  | '--nerey-shadow-sm'
  | '--nerey-shadow-md'
  | '--nerey-shadow-lg'
  | '--nerey-opacity-dimmed'
  | '--nerey-opacity-disabled';

export const NEREY_TOKENS: readonly NereyToken[] = [
  '--nerey-color-slate-50',
  '--nerey-color-slate-100',
  '--nerey-color-slate-200',
  '--nerey-color-slate-300',
  '--nerey-color-slate-400',
  '--nerey-color-slate-500',
  '--nerey-color-slate-600',
  '--nerey-color-slate-700',
  '--nerey-color-slate-800',
  '--nerey-color-slate-900',
  '--nerey-color-slate-950',
  '--nerey-color-teal-50',
  '--nerey-color-teal-100',
  '--nerey-color-teal-200',
  '--nerey-color-teal-300',
  '--nerey-color-teal-400',
  '--nerey-color-teal-500',
  '--nerey-color-teal-600',
  '--nerey-color-teal-700',
  '--nerey-color-teal-800',
  '--nerey-color-teal-900',
  '--nerey-color-teal-950',
  '--nerey-color-red-100',
  '--nerey-color-red-300',
  '--nerey-color-red-500',
  '--nerey-color-red-600',
  '--nerey-color-red-700',
  '--nerey-color-red-950',
  '--nerey-color-amber-100',
  '--nerey-color-amber-300',
  '--nerey-color-amber-500',
  '--nerey-color-amber-700',
  '--nerey-color-amber-950',
  '--nerey-color-green-100',
  '--nerey-color-green-300',
  '--nerey-color-green-500',
  '--nerey-color-green-700',
  '--nerey-color-green-950',
  '--nerey-color-white',
  '--nerey-color-black',
  '--nerey-space-0',
  '--nerey-space-1',
  '--nerey-space-2',
  '--nerey-space-3',
  '--nerey-space-4',
  '--nerey-space-5',
  '--nerey-space-6',
  '--nerey-space-8',
  '--nerey-space-10',
  '--nerey-space-12',
  '--nerey-space-16',
  '--nerey-radius-none',
  '--nerey-radius-sm',
  '--nerey-radius-md',
  '--nerey-radius-lg',
  '--nerey-radius-xl',
  '--nerey-radius-2xl',
  '--nerey-radius-full',
  '--nerey-font-sans',
  '--nerey-font-mono',
  '--nerey-font-size-xs',
  '--nerey-font-size-sm',
  '--nerey-font-size-md',
  '--nerey-font-size-lg',
  '--nerey-font-size-xl',
  '--nerey-line-height-tight',
  '--nerey-line-height-normal',
  '--nerey-line-height-relaxed',
  '--nerey-font-weight-normal',
  '--nerey-font-weight-medium',
  '--nerey-font-weight-semibold',
  '--nerey-letter-spacing-wide',
  '--nerey-duration-instant',
  '--nerey-duration-fast',
  '--nerey-duration-normal',
  '--nerey-ease-standard',
  '--nerey-ease-emphasized',
  '--nerey-z-raised',
  '--nerey-z-sticky',
  '--nerey-z-overlay',
  '--nerey-z-popover',
  '--nerey-z-toast',
  '--nerey-control-height-sm',
  '--nerey-control-height-md',
  '--nerey-control-height-lg',
  '--nerey-border-width',
  '--nerey-focus-ring-width',
  '--nerey-focus-ring-offset',
  '--nerey-widget-max-width',
  '--nerey-surface-canvas',
  '--nerey-surface-raised',
  '--nerey-surface-sunken',
  '--nerey-surface-muted',
  '--nerey-surface-inverse',
  '--nerey-surface-accent-subtle',
  '--nerey-surface-accent',
  '--nerey-surface-accent-hover',
  '--nerey-surface-danger-subtle',
  '--nerey-surface-danger',
  '--nerey-surface-danger-hover',
  '--nerey-surface-success-subtle',
  '--nerey-surface-warning-subtle',
  '--nerey-surface-hover',
  '--nerey-surface-selected',
  '--nerey-surface-scrim',
  '--nerey-text-primary',
  '--nerey-text-secondary',
  '--nerey-text-muted',
  '--nerey-text-disabled',
  '--nerey-text-inverse',
  '--nerey-text-on-accent',
  '--nerey-text-accent',
  '--nerey-text-danger',
  '--nerey-text-success',
  '--nerey-text-warning',
  '--nerey-text-link',
  '--nerey-border-subtle',
  '--nerey-border-default',
  '--nerey-border-strong',
  '--nerey-border-accent',
  '--nerey-border-danger',
  '--nerey-border-focus',
  '--nerey-shadow-sm',
  '--nerey-shadow-md',
  '--nerey-shadow-lg',
  '--nerey-opacity-dimmed',
  '--nerey-opacity-disabled',
] as const;

export const NEREY_SEMANTIC_TOKENS: readonly NereySemanticToken[] = [
  '--nerey-space-0',
  '--nerey-space-1',
  '--nerey-space-2',
  '--nerey-space-3',
  '--nerey-space-4',
  '--nerey-space-5',
  '--nerey-space-6',
  '--nerey-space-8',
  '--nerey-space-10',
  '--nerey-space-12',
  '--nerey-space-16',
  '--nerey-radius-none',
  '--nerey-radius-sm',
  '--nerey-radius-md',
  '--nerey-radius-lg',
  '--nerey-radius-xl',
  '--nerey-radius-2xl',
  '--nerey-radius-full',
  '--nerey-font-sans',
  '--nerey-font-mono',
  '--nerey-font-size-xs',
  '--nerey-font-size-sm',
  '--nerey-font-size-md',
  '--nerey-font-size-lg',
  '--nerey-font-size-xl',
  '--nerey-line-height-tight',
  '--nerey-line-height-normal',
  '--nerey-line-height-relaxed',
  '--nerey-font-weight-normal',
  '--nerey-font-weight-medium',
  '--nerey-font-weight-semibold',
  '--nerey-letter-spacing-wide',
  '--nerey-duration-instant',
  '--nerey-duration-fast',
  '--nerey-duration-normal',
  '--nerey-ease-standard',
  '--nerey-ease-emphasized',
  '--nerey-z-raised',
  '--nerey-z-sticky',
  '--nerey-z-overlay',
  '--nerey-z-popover',
  '--nerey-z-toast',
  '--nerey-control-height-sm',
  '--nerey-control-height-md',
  '--nerey-control-height-lg',
  '--nerey-border-width',
  '--nerey-focus-ring-width',
  '--nerey-focus-ring-offset',
  '--nerey-widget-max-width',
  '--nerey-surface-canvas',
  '--nerey-surface-raised',
  '--nerey-surface-sunken',
  '--nerey-surface-muted',
  '--nerey-surface-inverse',
  '--nerey-surface-accent-subtle',
  '--nerey-surface-accent',
  '--nerey-surface-accent-hover',
  '--nerey-surface-danger-subtle',
  '--nerey-surface-danger',
  '--nerey-surface-danger-hover',
  '--nerey-surface-success-subtle',
  '--nerey-surface-warning-subtle',
  '--nerey-surface-hover',
  '--nerey-surface-selected',
  '--nerey-surface-scrim',
  '--nerey-text-primary',
  '--nerey-text-secondary',
  '--nerey-text-muted',
  '--nerey-text-disabled',
  '--nerey-text-inverse',
  '--nerey-text-on-accent',
  '--nerey-text-accent',
  '--nerey-text-danger',
  '--nerey-text-success',
  '--nerey-text-warning',
  '--nerey-text-link',
  '--nerey-border-subtle',
  '--nerey-border-default',
  '--nerey-border-strong',
  '--nerey-border-accent',
  '--nerey-border-danger',
  '--nerey-border-focus',
  '--nerey-shadow-sm',
  '--nerey-shadow-md',
  '--nerey-shadow-lg',
  '--nerey-opacity-dimmed',
  '--nerey-opacity-disabled',
] as const;
