// GENERATED by scripts/gen-css-types.mjs from button.module.css — do not edit.
// Source: packages/theme/src/components/button/button.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly fullWidth: string;
  readonly ghost: string;
  readonly outline: string;
  readonly root: string;
  readonly sizeLg: string;
  readonly sizeSm: string;
  readonly solid: string;
  readonly toneDanger: string;
  readonly toneNeutral: string;
};
export default styles;
