// GENERATED by scripts/gen-css-types.mjs from text.module.css — do not edit.
// Source: packages/theme/src/widgets/text/text.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly root: string;
};
export default styles;
