// GENERATED by scripts/gen-css-types.mjs from slider.module.css — do not edit.
// Source: packages/theme/src/components/slider/slider.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly control: string;
  readonly indicator: string;
  readonly root: string;
  readonly thumb: string;
  readonly track: string;
  readonly value: string;
};
export default styles;
