// GENERATED by scripts/gen-css-types.mjs from select.module.css — do not edit.
// Source: packages/theme/src/components/select/select.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly group: string;
  readonly groupLabel: string;
  readonly icon: string;
  readonly item: string;
  readonly itemIndicator: string;
  readonly itemText: string;
  readonly popup: string;
  readonly popupSizeSm: string;
  readonly positioner: string;
  readonly scrollArrow: string;
  readonly scrollArrowDown: string;
  readonly scrollArrowUp: string;
  readonly trigger: string;
  readonly triggerSizeSm: string;
  readonly value: string;
};
export default styles;
