// GENERATED by scripts/gen-css-types.mjs from checkbox.module.css — do not edit.
// Source: packages/theme/src/components/checkbox/checkbox.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly dash: string;
  readonly group: string;
  readonly indicator: string;
  readonly root: string;
  readonly tick: string;
};
export default styles;
