// GENERATED by scripts/gen-css-types.mjs from badge.module.css — do not edit.
// Source: packages/theme/src/components/badge/badge.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly outline: string;
  readonly root: string;
  readonly sizeSm: string;
  readonly solid: string;
  readonly toneAccent: string;
  readonly toneDanger: string;
  readonly toneSuccess: string;
  readonly toneWarning: string;
};
export default styles;
