// GENERATED by scripts/gen-css-types.mjs from confirmation.module.css — do not edit.
// Source: packages/theme/src/widgets/confirmation/confirmation.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly icon: string;
  readonly root: string;
  readonly toneDanger: string;
};
export default styles;
