// GENERATED by scripts/gen-css-types.mjs from stack.module.css — do not edit.
// Source: packages/theme/src/components/stack/stack.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly alignBaseline: string;
  readonly alignCenter: string;
  readonly alignEnd: string;
  readonly alignStart: string;
  readonly gap1: string;
  readonly gap2: string;
  readonly gap3: string;
  readonly gap4: string;
  readonly gap6: string;
  readonly gap8: string;
  readonly justifyAround: string;
  readonly justifyBetween: string;
  readonly justifyCenter: string;
  readonly justifyEnd: string;
  readonly root: string;
  readonly row: string;
  readonly wrap: string;
};
export default styles;
