// GENERATED by scripts/gen-css-types.mjs from collapsible.module.css — do not edit.
// Source: packages/theme/src/components/collapsible/collapsible.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly indicator: string;
  readonly panel: string;
  readonly panelContent: string;
  readonly root: string;
  readonly trigger: string;
  readonly triggerLabel: string;
};
export default styles;
