// GENERATED by scripts/gen-css-types.mjs from task-tree.module.css — do not edit.
// Source: packages/theme/src/widgets/task-tree/task-tree.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly chevron: string;
  readonly detail: string;
  readonly detailDanger: string;
  readonly empty: string;
  readonly group: string;
  readonly header: string;
  readonly item: string;
  readonly label: string;
  readonly marker: string;
  readonly root: string;
  readonly row: string;
  readonly rowActionable: string;
  readonly statusDone: string;
  readonly statusError: string;
  readonly statusRunning: string;
  readonly statusSkipped: string;
  readonly streaming: string;
  readonly tree: string;
};
export default styles;
