// GENERATED by scripts/gen-css-types.mjs from data-table.module.css — do not edit.
// Source: packages/theme/src/widgets/data-table/data-table.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly alignEnd: string;
  readonly caption: string;
  readonly cell: string;
  readonly empty: string;
  readonly emptyCell: string;
  readonly header: string;
  readonly numeric: string;
  readonly root: string;
  readonly row: string;
  readonly scroller: string;
  readonly sort: string;
  readonly sortGlyph: string;
  readonly sortLabel: string;
  readonly table: string;
};
export default styles;
