// GENERATED by scripts/gen-css-types.mjs from meter.module.css — do not edit.
// Source: packages/theme/src/components/meter/meter.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly indicator: string;
  readonly label: string;
  readonly root: string;
  readonly sizeSm: string;
  readonly toneDanger: string;
  readonly toneSuccess: string;
  readonly toneWarning: string;
  readonly track: string;
  readonly value: string;
};
export default styles;
