// GENERATED by scripts/gen-css-types.mjs from citations.module.css — do not edit.
// Source: packages/theme/src/widgets/citations/citations.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly citation: string;
  readonly claim: string;
  readonly empty: string;
  readonly link: string;
  readonly linkHost: string;
  readonly marker: string;
  readonly root: string;
};
export default styles;
