// GENERATED by scripts/gen-css-types.mjs from separator.module.css — do not edit.
// Source: packages/theme/src/components/separator/separator.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly horizontal: string;
  readonly labelled: string;
  readonly root: string;
  readonly vertical: string;
};
export default styles;
