// GENERATED by scripts/gen-css-types.mjs from surface.module.css — do not edit.
// Source: packages/theme/src/components/surface/surface.module.css. Run `npm run gen:css-types` after adding or renaming a class (ADR 0023).

declare const styles: {
  readonly ghost: string;
  readonly outline: string;
  readonly padLg: string;
  readonly padNone: string;
  readonly padSm: string;
  readonly radiusMd: string;
  readonly radiusXl: string;
  readonly raised: string;
  readonly root: string;
  readonly sunken: string;
};
export default styles;
